version: "v1.0"

debug: "${debug}"
num_workers: "${num_workers}"

device: "cuda:0"

eval_only: false
random_seed: 1
num_points: 4096
# feature channels, excluding xyz
num_channels: 6
has_normal: True
has_color: True

augmentation:
  jitter: false
  flip: false
  rotate: false
  color: false

test_split: "test"

stage1:
  name: "stage1"
  run: true
  eval_only: "${network.eval_only}"
  random_seed: "${network.random_seed}"
  paths: "${paths.network.stage1}"
  device: "${network.device}"
  debug: "${network.debug}"
  num_points: "${network.num_points}"
  num_workers: "${network.num_workers}"
  num_channels: "${network.num_channels}"
  augmentation: "${network.augmentation}"
  has_normal: "${network.has_normal}"
  has_color: "${network.has_color}"

  train:
    continuous: false
    input_data: path
    input_model: path
    save_frequency: 5
    log_frequency: 1

    max_epochs: 500
    lr: 0.001
    batch_size: 8

    # Loss weights
    loss_weight:
      anchor_pts_loss: 1.0
      joint_direction_cat_loss: 1.0
      joint_direction_reg_loss: 100.0
      joint_origin_reg_loss: 1.0
      joint_type_loss: 1.0
      simmat_loss: 1.0
      confidence_loss: 100.0
  
  test:
    split: "${network.test_split}"
    input_data: path
    inference_model: path
    batch_size: 1
    with_best: false

  postprocess: ${postprocess.stage1}

stage2:
  name: "stage2"
  run: true
  eval_only: "${network.eval_only}"
  random_seed: "${network.random_seed}"
  paths: "${paths.network.stage2}"
  device: "${network.device}"
  debug: "${network.debug}"
  num_points: "${network.num_points}"
  num_workers: "${network.num_workers}"
  num_channels: "${network.num_channels}"
  augmentation: "${network.augmentation}"
  has_normal: "${network.has_normal}"
  has_color: "${network.has_color}"

  train:
    continuous: false
    input_data: path
    input_model: path
    save_frequency: 5
    log_frequency: 1

    max_epochs: 100
    lr: 0.001
    batch_size: 16

    loss_weight:
      motion_scores_loss: 1.0

  test:
    split: "${network.test_split}"
    input_data: path
    inference_model: path
    batch_size: 1
    with_best: false
  
  model:
    pretrained_module: ["backbone", "motion_feat", "simmat_feat"]
  
  postprocess: ${postprocess.stage2}

stage3:
  name: "stage3"
  run: true
  eval_only: "${network.eval_only}"
  random_seed: "${network.random_seed}"
  paths: "${paths.network.stage3}"
  device: "${network.device}"
  debug: "${network.debug}"
  num_points: "${network.num_points}"
  num_workers: "${network.num_workers}"
  num_channels: "${network.num_channels}"
  augmentation: "${network.augmentation}"
  has_normal: "${network.has_normal}"
  has_color: "${network.has_color}"

  train:
    continuous: false
    input_data: path
    input_model: path
    save_frequency: 5
    log_frequency: 1

    max_epochs: 100
    lr: 0.001
    batch_size: 8

    loss_weight:
      part_proposal_loss: 1.0
      motion_regression_loss: 1.0

  test:
    split: "${network.test_split}"
    input_data: path
    inference_model: path
    batch_size: 1
    with_best: false

  postprocess: ${postprocess.stage3}
