name: "MULTISCAN"

input:
  folder_name: "multiscan"
  path: "dataset/multiscan"
  train_set: "articulated_objects.train.h5"
  val_set: "articulated_objects.val.h5"
  test_set: "articulated_objects.test.h5"
  file_ext: ".h5"