version: "1.0"

dataset_dir: "${dataset.input.path}" # path to datasets folder
result_dir: results # path to result folder

preprocess:
  input_dir: "${paths.dataset_dir}"
  output_dir: "${paths.result_dir}/preprocess"
  tmp_dir: "${paths.preprocess.output_dir}/tmp"

  input: ${dataset.input} # overwrite based on dataset selection at runtime
  tmp_output:
    path: "${paths.preprocess.tmp_dir}"
    input_files: "input_files.csv"
  output:
    path: "${paths.preprocess.output_dir}"
    split_info: "split_info.csv"
    train_data: "train.h5"
    val_data: "val.h5"
    test_data: "test.h5"

    train: "${paths.preprocess.output_dir}/${paths.preprocess.output.train_data}"
    val: "${paths.preprocess.output_dir}/${paths.preprocess.output.val_data}"
    test: "${paths.preprocess.output_dir}/${paths.preprocess.output.test_data}"

network:
  output_dir: "${paths.result_dir}/network"
  stage1:
    folder_name: "stage1"
    path: "${paths.network.output_dir}/${paths.network.stage1.folder_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}"
    train:
      output_dir: "${paths.network.stage1.path}/train"
      model_filename: "model_%09d.pth"
      best_model_filename: "best_model.pth"
    inference:
      output_dir: "${paths.network.stage1.path}/inference"
      inference_result: "inference_result.h5"