version: "v1.0"

debug: false
num_workers: 16

defaults:
  - paths: default
  - _self_ # https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order

test_split: "val"
iou_threshold: 0.5
output_dir: "${paths.result_dir}/evaluation"
eval_train: False

inst_pred_path:

# hydra configuration log output dir
hydra:
  run:
    dir: "${paths.result_dir}/logs/${now:%Y-%m-%d}/${now:%H-%M-%S}"