version: "v1.0"

debug: false
show: false
export: false
num_workers: 16

defaults:
  - dataset: shape2motion
  - paths: default
  - _self_ # https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order

split:
  train_percent: 0.6
  split_seed: 1
  train:
    input_file_indices: [0]
    num_instances: 1
  val:
    input_file_indices: [0]
    num_instances: 1
  test:
    input_file_indices: [0]
    num_instances: 1

stage: "stage1"

# hydra configuration log output dir
hydra:
  run:
    dir: "${paths.preprocess.output_dir}/logs/${now:%Y-%m-%d}/${now:%H-%M-%S}"